config/routes.rb
Rails.application.routes.draw do
  devise_for :students
  devise_for :teachers
  devise_for :admins
  root to: 'dashboard#index'
  get 'dashboard/index' => 'dashboard#index'

  resources :subjects
  resources :courses
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :trackable, :validatable
end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :students
end

app/models/student.rb
class Student < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
  belongs_to :course
  has_many :student_subjects, dependent: :destroy
  has_many :subjects, through: :student_subjects
end

app/models/student_subject.rb
class StudentSubject < ActiveRecord::Base
  belongs_to :student
  belongs_to :subject
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :student_subjects, dependent: :destroy
  has_many :students, through: :student_subjects
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :trackable, :validatable
  has_many :teacher_subjects, dependent: :destroy
end

app/models/teacher_subject.rb
class TeacherSubject < ActiveRecord::Base
  belongs_to :teacher
  belongs_to :subject
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include CRUDFeature

  devise_group :user, contains: [:admin, :teacher, :student]

  def after_sign_in_path_for(resource)
    dashboard_index_path
  end

  def after_sign_out_path_for(resource)
    send("new_#{resource.to_s}_session_path")
  end
end

app/controllers/concerns/crud_feature.rb
module CRUDFeature
  extend ActiveSupport::Concern
  included do
    before_action :set_resource, only: [:show, :edit, :update, :destroy]

    def index
      @resources = model_class.all
      render :index
    end

    def new
      @resource = new_resource
    end

    def show
      render :show
    end

    def edit
      render :edit
    end

    def create
      @resource = new_resource(permitted_params)
      if @resource.save
        redirect_to @resource
      else
        render :edit
      end
    end

    def update
      if @resource.update(permitted_params)
        redirect_to @resource
      else
        render :new
      end
    end

    protected

    def namespace
      self.class.name.deconstantize
    end

    def model_class
      if namespace.present?
        "#{namespace}::#{controller_name.classify}".constantize
      else
        "#{controller_name.classify}".constantize
      end
    end

    def new_resource(*args)
      model_class.new(*args)
    end

    def excluded_params
      %w(id create_at updated_at created_by updated_by)
    end

    def permitted_params
      params.require(model_class.name.underscore.split('/').join('_').to_sym).permit(model_class.column_names - excluded_params)
    end

    def set_resource
      @resource = model_class.find(params[:id])
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index

  end
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/courses/_form.html.haml
= form_for @resource do |f|
  - if @resource.errors.any?
    #error_explanation
      %h2= "#{pluralize(@resource.errors.count, "error")} prohibited this course from being saved:"
      %ul
        - @resource.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :code
    = f.text_field :code
  .actions
    = f.submit 'Save'

app/views/courses/edit.html.haml
%h1 Editing course

= render 'form'

= link_to 'Show', @course
\|
= link_to 'Back', courses_path

app/views/courses/index.html.haml
%h1 Listing courses

%table
  %thead
    %tr
      %th Name
      %th
      %th

  %tbody
    - @resources.each do |course|
      %tr
        %td= course.code
        %td= link_to 'Show', course
        %td= link_to 'Edit', '#'

%br

app/views/courses/new.html.haml
%h1 New course

= render 'form'

= link_to 'Back', courses_path

app/views/courses/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @resource.name

= link_to 'Edit', '#'
\|
= link_to 'Back', '#'

app/views/dashboard/index.html.haml
%h1 Dashboard Page

app/views/layouts/_navigation_top.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} Brand
    / Collect the nav links, forms, and other content for toggling
    -if user_signed_in?
      #bs-example-navbar-collapse-1.collapse.navbar-collapse
        %ul.nav.navbar-nav
          %li.active
            %a{:href => "#"}
              Link
              %span.sr-only (current)
          %li
            %a{:href => "#"} Link
          %li.dropdown
            %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
              Dropdown
              %span.caret
            %ul.dropdown-menu
              %li
                %a{:href => "#"} Action
              %li
                %a{:href => "#"} Another action
              %li
                %a{:href => "#"} Something else here
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} Separated link
              %li.divider{:role => "separator"}
              %li
                %a{:href => "#"} One more separated link
        %ul.nav.navbar-nav.navbar-right
          %li
            %a{:href => "#"}
          %li
            = link_to send("destroy_#{current_user.class.name.downcase}_session_path"), method: :delete do
              %i.glyphicon.glyphicon-lock
              = t 'helpers.links.logout', default: 'Logout'
      / /.navbar-collapse
    / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html{:lang => I18n.locale}
  %head
    %meta{:charset => "utf-8"}/
    %title
      = yield :title
      | #{t 'system_name', default: 'Must Buy System'}
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    =render 'layouts/navigation_top.html'
    .container
      = yield
    =javascript_tag "window.locale = #{I18n.locale.to_s.inspect};"
    = javascript_include_tag 'application'

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name)
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to "Forgot your password?", new_password_path(resource_name)
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider)
    %br/